class MoedaStatic {
  static const Map<String, String> moedaStatic = {
    'THB-BRL': 'Baht Tailandês',
    'BTC-BRL': 'Bitcoin',
    'VEF-BRL': 'Bolívar Venezuelano',
    'BOB-BRL': 'Boliviano',
    'DKK-BRL': 'Coroa Dinamarquesa',
    'NOK-BRL': 'Coroa Norueguesa',
    'SEK-BRL': 'Coroa Sueca',
    'AED-BRL': 'Dirham dos Emirados',
    'DOGE-BRL': 'Dogecoin',
    'USD-BRL': 'Dólar Americano',
    'USDT-BRL': 'Dólar Americano (USDT)',
    'AUD-BRL': 'Dólar Australiano',
    'CAD-BRL': 'Dólar Canadense',
    'SGD-BRL': 'Dólar de Cingapura',
    'HKD-BRL': 'Dólar de Hong Kong',
    'NZD-BRL': 'Dólar Neozelandês',
    'TWD-BRL': 'Dólar Taiwanês',
    'ETH-BRL': 'Ethereum',
    'EUR-BRL': 'Euro',
    'CHF-BRL': 'Franco Suíço',
    'PYG-BRL': 'Guarani Paraguaio',
    'JPY-BRL': 'Iene Japonês',
    'GBP-BRL': 'Libra Esterlina',
    'LTC-BRL': 'Litecoin',
    'TRY-BRL': 'Nova Lira Turca',
    'ILS-BRL': 'Novo Shekel Israelense',
    'ARS-BRL': 'Peso Argentino',
    'CLP-BRL': 'Peso Chileno',
    'COP-BRL': 'Peso Colombiano',
    'MXN-BRL': 'Peso Mexicano',
    'UYU-BRL': 'Peso Uruguaio',
    'ZAR-BRL': 'Rand Sul-Africano',
    'SAR-BRL': 'Riyal Saudita',
    'RUB-BRL': 'Rublo Russo1',
    'INR-BRL': 'Rupia Indiana',
    'PEN-BRL': 'Sol do Peru',
    'CNY-BRL': 'Yuan Chinês'
  };
}
