class MoedaStatic {
  static const List<Map<String, String>> moedaStatic = [
    {
      'BRL-AFN': 'Afghani do Afeganistão',
      'BRL-MGA': 'Ariary Madagascarense',
      'BRL-PAB': 'Balboa Panamenho',
      'BRL-THB': 'Baht Tailandês',
      'BRL-BTC': 'Bitcoin',
      'BRL-ETB': 'Birr Etíope',
      'BRL-VEF': 'Bolívar Venezuelano',
      'BRL-BOB': 'Boliviano',
      'BRL-XBR': 'Brent Spot',
      'BRL-GHS': 'Cedi Ganês',
      'BRL-CRC': 'Colón Costarriquenho',
      'BRL-CZK': 'Coroa Checa',
      'BRL-DKK': 'Coroa Dinamarquesa',
      'BRL-ISK': 'Coroa Islandesa',
      'BRL-NOK': 'Coroa Norueguesa',
      'BRL-SEK': 'Coroa Sueca',
      'BRL-GMD': 'Dalasi da Gâmbia',
      'BRL-MKD': 'Denar Macedônio',
      'BRL-DZD': 'Dinar Argelino',
      'BRL-BHD': 'Dinar do Bahrein',
      'BRL-IQD': 'Dinar Iraquiano',
      'BRL-JOD': 'Dinar Jordaniano',
      'BRL-KWD': 'Dinar Kuwaitiano',
      'BRL-RSD': 'Dinar Sérvio',
      'BRL-TND': 'Dinar Tunisiano',
      'BRL-AED': 'Dirham dos Emirados',
      'BRL-MAD': 'Dirham Marroquino',
      'BRL-DOGE': 'Dogecoin',
      'BRL-USD': 'Dólar Americano',
      'BRL-USDT': 'Dólar Americano',
      'BRL-AUD': 'Dólar Australiano',
      'BRL-CAD': 'Dólar Canadense',
      'BRL-BSD': 'Dólar das Bahamas',
      'BRL-ARS': 'Peso Argentino',
      'BRL-CHF': 'Franco Suíço',
      'BRL-CLP': 'Peso Chileno',
      'BRL-HKD': 'Dólar de Hong Kong',
      'BRL-JPY': 'Iene Japonês',
      'BRL-MXN': 'Peso Mexicano',
      'BRL-SGD': 'Dólar de Cingapura',
      'BRL-BBD': 'Dólar de Barbados',
      'BRL-CNY': 'Yuan Chinês',
      'BRL-EGP': 'Libra Egípcia',
      'BRL-GBP': 'Libra Esterlina',
      'BRL-HUF': 'Florim Húngaro',
      'BRL-IDR': 'Rupia Indonésia',
      'BRL-ILS': 'Novo Shekel Israelense',
      'BRL-INR': 'Rúpia Indiana',
      'BRL-JMD': 'Dólar Jamaicano',
      'BRL-KES': 'Shilling Queniano',
      'BRL-KRW': 'Won Sul-Coreano',
      'BRL-LBP': 'Libra Libanesa',
      'BRL-LKR': 'Rúpia de Sri Lanka',
      'BRL-MYR': 'Ringgit Malaio',
      'BRL-NAD': 'Dólar Namíbio',
      'BRL-NPR': 'Rúpia Nepalesa',
      'BRL-NZD': 'Dólar Neozelandês',
      'BRL-OMR': 'Rial Omanense',
      'BRL-PHP': 'Peso Filipino',
      'BRL-PKR': 'Rúpia Paquistanesa',
      'BRL-PLN': 'Zlóti Polonês',
      'BRL-QAR': 'Rial Catarense',
      'BRL-RON': 'Leu Romeno',
      'BRL-RUB': 'Rublo Russo',
      'BRL-SAR': 'Riyal Saudita',
      'BRL-TRY': 'Nova Lira Turca',
      'BRL-XAF': 'Franco CFA Central',
      'BRL-XCD': 'Dólar do Caribe Oriental',
      'BRL-XOF': 'Franco CFA Ocidental',
      'BRL-ZAR': 'Rand Sul-Africano',
      'BRL-TWD': 'Dólar Taiuanês',
      'BRL-PYG': 'Guarani Paraguaio',
      'BRL-UYU': 'Peso Uruguaio',
      'BRL-COP': 'Peso Colombiano',
      'BRL-PEN': 'Sol do Peru',
      'BRL-ALL': 'Lek Albanês',
      'BRL-AMD': 'Dram Armênio',
      'BRL-ANG': 'Guilder das Antilhas',
      'BRL-AOA': 'Kwanza Angolano',
      'BRL-AZN': 'Manat Azeri',
      'BRL-BAM': 'Marco Conversível',
      'BRL-BDT': 'Taka de Bangladesh',
      'BRL-BGN': 'Lev Búlgaro',
      'BRL-BIF': 'Franco Burundinense',
      'BRL-BND': 'Dólar de Brunei',
      'BRL-BRLT': 'Real Brasileiro Turismo',
      'BRL-BWP': 'Pula de Botswana',
      'BRL-BYN': 'Rublo Bielorrusso',
      'BRL-BZD': 'Dólar de Belize',
      'BRL-CHFRTS': 'Franco Suíço',
      'BRL-CNH': 'Yuan chinês offshore',
      'BRL-CUP': 'Peso Cubano',
      'BRL-CVE': 'Escudo cabo-verdiano',
      'BRL-DJF': 'Franco do Djubouti',
      'BRL-DOP': 'Peso Dominicano',
      'BRL-ETH': 'Ethereum',
      'BRL-EUR': 'Euro',
      'BRL-FJD': 'Dólar de Fiji',
      'BRL-GEL': 'Lari Georgiano',
      'BRL-GNF': 'Franco de Guiné',
      'BRL-GTQ': 'Quetzal Guatemalteco',
      'BRL-HNL': 'Lempira Hondurenha',
      'BRL-HRK': 'Kuna Croata',
      'BRL-HTG': 'Gourde Haitiano',
      'BRL-IRR': 'Rial Iraniano',
      'BRL-JPYRTS': 'Iene Japonês',
      'BRL-KGS': 'Som Quirguistanês',
      'BRL-KHR': 'Riel Cambojano',
      'BRL-KMF': 'Franco Comorense',
      'BRL-KYD': 'Dólar das Ilhas Cayman',
      'BRL-KZT': 'Tengue Cazaquistanês',
      'BRL-LAK': 'Kip Laosiano',
      'BRL-LSL': 'Loti do Lesoto',
      'BRL-LTC': 'Litecoin',
      'BRL-LYD': 'Dinar Líbio',
      'BRL-MDL': 'Leu Moldavo',
      'BRL-MMK': 'Kyat de Mianmar',
      'BRL-MNT': 'Mongolian Tugrik',
      'BRL-MOP': 'Pataca de Macau',
      'BRL-MRO': 'Ouguiya Mauritana',
      'BRL-MUR': 'Rúpia Mauriciana',
      'BRL-MVR': 'Rufiyaa Maldiva',
      'BRL-MWK': 'Kwacha Malauiana',
      'BRL-MZN': 'Metical de Moçambique',
      'BRL-NGN': 'Naira Nigeriana',
      'BRL-NGNI': 'Naira Nigeriana',
      'BRL-NGNPARALLEL': 'Naira Nigeriana',
      'BRL-NIO': 'Córdoba Nicaraguense',
      'BRL-PGK': 'Kina Papua-Nova Guiné',
      'BRL-RUBTOD': 'Rublo Russo',
      'BRL-RUBTOM': 'Rublo Russo',
      'BRL-RWF': 'Franco Ruandês',
      'BRL-SCR': 'Rúpias de Seicheles',
      'BRL-SDG': 'Libra Sudanesa',
      'BRL-SDR': 'DSE',
      'BRL-SOS': 'Shilling Somaliano',
      'BRL-STD': 'Dobra São Tomé/Príncipe',
      'BRL-SVC': 'Colon de El Salvador',
      'BRL-SYP': 'Libra Síria',
      'BRL-SZL': 'Lilangeni Suazilandês',
      'BRL-TJS': 'Somoni do Tajiquistão',
      'BRL-TMT': 'TMT',
      'BRL-TTD': 'Dólar de Trinidad',
      'BRL-TZS': 'Shilling Tanzaniano',
      'BRL-UAH': 'Hryvinia Ucraniana',
      'BRL-UGX': 'Shilling Ugandês',
      'BRL-UZS': 'Som Uzbequistanês',
      'BRL-VND': 'Dong Vietnamita',
      'BRL-VUV': 'Vatu de Vanuatu',
      'BRL-XAGG': 'Prata',
      'BRL-XPF': 'Franco CFP',
      'BRL-XRP': 'XRP',
      'BRL-YER': 'Riyal Iemenita',
      'BRL-ZMK': 'Kwacha Zambiana',
      'BRL-ZWL': 'Dólar Zimbabuense',
      'BRL-XAU': 'Ouro',
    }
  ];
}
