class MoedaStatic {
  static const Map<String, String> moedaStatic = {
    'BRL-AFN': 'Afghani do Afeganistão',
    'BRL-MGA': 'Ariary Madagascarense',
    'BRL-PAB': 'Balboa Panamenho',
    'BRL-THB': 'Baht Tailandês',
    'BRL-BTC': 'Bitcoin',
    'BRL-ETB': 'Birr Etíope',
    'BRL-VEF': 'Bolívar Venezuelano',
    'BRL-BOB': 'Boliviano',
    'BRL-XBR': 'Brent Spot',
    'BRL-GHS': 'Cedi Ganês',
    'BRL-SVC': 'Colon de El Salvador',
    'BRL-CRC': 'Colón Costarriquenho',
    'BRL-NIO': 'Córdoba Nicaraguense',
    'BRL-CZK': 'Coroa Checa',
    'BRL-DKK': 'Coroa Dinamarquesa',
    'BRL-ISK': 'Coroa Islandesa',
    'BRL-NOK': 'Coroa Norueguesa',
    'BRL-SEK': 'Coroa Sueca',
    'BRL-GMD': 'Dalasi da Gâmbia',
    'BRL-MKD': 'Denar Macedônio',
    'BRL-DZD': 'Dinar Argelino',
    'BRL-BHD': 'Dinar do Bahrein',
    'BRL-IQD': 'Dinar Iraquiano',
    'BRL-JOD': 'Dinar Jordaniano',
    'BRL-KWD': 'Dinar Kuwaitiano',
    'BRL-LYD': 'Dinar Líbio',
    'BRL-RSD': 'Dinar Sérvio',
    'BRL-TND': 'Dinar Tunisiano',
    'BRL-AED': 'Dirham dos Emirados',
    'BRL-MAD': 'Dirham Marroquino',
    'BRL-DOGE': 'Dogecoin',
    'BRL-USD': 'Dólar Americano',
    'BRL-USDT': 'Dólar Americano',
    'BRL-AUD': 'Dólar Australiano',
    'BRL-CAD': 'Dólar Canadense',
    'BRL-BSD': 'Dólar das Bahamas',
    'BRL-KYD': 'Dólar das Ilhas Cayman',
    'BRL-BZD': 'Dólar de Belize',
    'BRL-BND': 'Dólar de Brunei',
    'BRL-SGD': 'Dólar de Cingapura',
    'BRL-FJD': 'Dólar de Fiji',
    'BRL-HKD': 'Dólar de Hong Kong',
    'BRL-TTD': 'Dólar de Trinidad',
    'BRL-XCD': 'Dólar do Caribe Oriental',
    'BRL-JMD': 'Dólar Jamaicano',
    'BRL-NAD': 'Dólar Namíbio',
    'BRL-NZD': 'Dólar Neozelandês',
    'BRL-TWD': 'Dólar Taiuanês',
    'BRL-ZWL': 'Dólar Zimbabuense',
    'BRL-VND': 'Dong Vietnamita',
    'BRL-STD': 'Dobra São Tomé/Príncipe',
    'BRL-AMD': 'Dram Armênio',
    'BRL-SDR': 'DSE',
    'BRL-CVE': 'Escudo cabo-verdiano',
    'BRL-ETH': 'Ethereum',
    'BRL-EUR': 'Euro',
    'BRL-HUF': 'Florim Húngaro',
    'BRL-BIF': 'Franco Burundinense',
    'BRL-XAF': 'Franco CFA Central',
    'BRL-XOF': 'Franco CFA Ocidental',
    'BRL-XPF': 'Franco CFP',
    'BRL-KMF': 'Franco Comorense',
    'BRL-GNF': 'Franco de Guiné',
    'BRL-DJF': 'Franco do Djubouti',
    'BRL-RWF': 'Franco Ruandês',
    'BRL-CHFRTS': 'Franco Suíço',
    'BRL-CHF': 'Franco Suíço',
    'BRL-HTG': 'Gourde Haitiano',
    'BRL-PYG': 'Guarani Paraguaio',
    'BRL-ANG': 'Guilder das Antilhas',
    'BRL-UAH': 'Hryvinia Ucraniana',
    'BRL-JPY': 'Iene Japonês',
    'BRL-JPYRTS': 'Iene Japonês',
    'BRL-PGK': 'Kina Papua-Nova Guiné',
    'BRL-LAK': 'Kip Laosiano',
    'BRL-HRK': 'Kuna Croata',
    'BRL-MWK': 'Kwacha Malauiana',
    'BRL-ZMK': 'Kwacha Zambiana',
    'BRL-AOA': 'Kwanza Angolano',
    'BRL-MMK': 'Kyat de Mianmar',
    'BRL-GEL': 'Lari Georgiano',
    'BRL-MDL': 'Leu Moldavo',
    'BRL-RON': 'Leu Romeno',
    'BRL-EGP': 'Libra Egípcia',
    'BRL-GBP': 'Libra Esterlina',
    'BRL-LBP': 'Libra Libanesa',
    'BRL-SDG': 'Libra Sudanesa',
    'BRL-SYP': 'Libra Síria',
    'BRL-SZL': 'Lilangeni Suazilandês',
    'BRL-LTC': 'Litecoin',
    'BRL-HNL': 'Lempira Hondurenha',
    'BRL-ALL': 'Lek Albanês',
    'BRL-BGN': 'Lev Búlgaro',
    'BRL-LSL': 'Loti do Lesoto',
    'BRL-AZN': 'Manat Azeri',
    'BRL-BAM': 'Marco Conversível',
    'BRL-MZN': 'Metical de Moçambique',
    'BRL-MNT': 'Mongolian Tugrik',
    'BRL-NGNI': 'Naira Nigeriana',
    'BRL-NGNPARALLEL': 'Naira Nigeriana',
    'BRL-NGN': 'Naira Nigeriana',
    'BRL-TRY': 'Nova Lira Turca',
    'BRL-ILS': 'Novo Shekel Israelense',
    'BRL-MRO': 'Ouguiya Mauritana',
    'BRL-XAU': 'Ouro',
    'BRL-MOP': 'Pataca de Macau',
    'BRL-ARS': 'Peso Argentino',
    'BRL-CLP': 'Peso Chileno',
    'BRL-COP': 'Peso Colombiano',
    'BRL-CUP': 'Peso Cubano',
    'BRL-DOP': 'Peso Dominicano',
    'BRL-PHP': 'Peso Filipino',
    'BRL-MXN': 'Peso Mexicano',
    'BRL-UYU': 'Peso Uruguaio',
    'BRL-BWP': 'Pula de Botswana',
    'BRL-XAGG': 'Prata',
    'BRL-GTQ': 'Quetzal Guatemalteco',
    'BRL-ZAR': 'Rand Sul-Africano',
    'BRL-BRLT': 'Real Brasileiro Turismo',
    'BRL-QAR': 'Rial Catarense',
    'BRL-IRR': 'Rial Iraniano',
    'BRL-OMR': 'Rial Omanense',
    'BRL-KHR': 'Riel Cambojano',
    'BRL-MYR': 'Ringgit Malaio',
    'BRL-YER': 'Riyal Iemenita',
    'BRL-SAR': 'Riyal Saudita',
    'BRL-BYN': 'Rublo Bielorrusso',
    'BRL-RUB': 'Rublo Russo',
    'BRL-RUBTOD': 'Rublo Russo',
    'BRL-RUBTOM': 'Rublo Russo',
    'BRL-MVR': 'Rufiyaa Maldiva',
    'BRL-LKR': 'Rúpia de Sri Lanka',
    'BRL-SCR': 'Rúpias de Seicheles',
    'BRL-INR': 'Rúpia Indiana',
    'BRL-IDR': 'Rúpia Indonésia',
    'BRL-MUR': 'Rúpia Mauriciana',
    'BRL-NPR': 'Rúpia Nepalesa',
    'BRL-PKR': 'Rúpia Paquistanesa',
    'BRL-KES': 'Shilling Queniano',
    'BRL-SOS': 'Shilling Somaliano',
    'BRL-TZS': 'Shilling Tanzaniano',
    'BRL-UGX': 'Shilling Ugandês',
    'BRL-PEN': 'Sol do Peru',
    'BRL-KGS': 'Som Quirguistanês',
    'BRL-UZS': 'Som Uzbequistanês',
    'BRL-TJS': 'Somoni do Tajiquistão',
    'BRL-BDT': 'Taka de Bangladesh',
    'BRL-KZT': 'Tengue Cazaquistanês',
    'BRL-TMT': 'TMT',
    'BRL-VUV': 'Vatu de Vanuatu',
    'BRL-KRW': 'Won Sul-Coreano',
    'BRL-XRP': 'XRP',
    'BRL-CNY': 'Yuan Chinês',
    'BRL-CNH': 'Yuan Chinês offshore',
    'BRL-PLN': 'Zlóti Polonês',
  };
}
